import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Inconsolata, Raleway } from "next/font/google"; // Correctly imported

import "./globals.css";

import { ThemeProvider } from "@/components/theme-provider";

// Configure Geist Sans (already correct)
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// Configure Geist Mono (already correct)
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// --- FIX: Configure your new fonts ---
const inconsolata = Inconsolata({
  variable: "--font-inconsolata",
  subsets: ["latin"],
  display: 'swap', // Good practice for performance
});

const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
  display: 'swap', // Good practice for performance
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      {/* --- FIX: Add the new font variables to the body's className --- */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inconsolata.variable} ${raleway.variable} font-sans antialiased`}
      >
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
        {children}
        </ThemeProvider>
      </body>
    </html>
  );
}